### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by TAFTpyro** [Strezzed/MavenMCP#13]
I just tried using mavenmcp on my OSX laptop but I got the following error:
`Installing MavenMCP
Downloading MCP...
./install.sh: line 16: wget: command not found
Unzipping MCP...
unzip:  cannot find or open mcp.zip, mcp.zip.zip or mcp.zip.ZIP.
Executing MCP...
python: can't open file './runtime/decompile.py': [Errno 2] No such file or directory
Copying Sources...
cp: tmp/src/minecraft/: No such file or directory
Rearrange...
mv: rename src/main/java/Start.java to src/main/java/net/minecraft/Start.java: No such file or directory
Copying workspace...
cp: tmp/jars/: No such file or directory
Clean Up...
Done.`

**Comment by TAFTpyro** [comment]
Installing MavenMCP
Downloading MCP...
./install.sh: line 16: wget: command not found
Unzipping MCP...
unzip:  cannot find or open mcp.zip, mcp.zip.zip or mcp.zip.ZIP.
Executing MCP...
python: can't open file './runtime/decompile.py': [Errno 2] No such file or directory
Copying Sources...
cp: tmp/src/minecraft/: No such file or directory
Rearrange...
mv: rename src/main/java/Start.java to src/main/java/net/minecraft/Start.java: No such file or directory
Copying workspace...
cp: tmp/jars/: No such file or directory
Clean Up...
Done.

**Comment by bddvlpr** [comment]
Install wget

`brew install wget`

**Comment by TAFTpyro** [comment]
Thanks! It works now! Maybe you could add something to the README.md that will say something along the lines of 'wget is needed' or something like that
