### ISSUE TITLE
how to run client

### ISSUE THREAD

**Issue by ghost** [Strezzed/MavenMCP#25]
I tried `mvn clean install` and then `java -jar ./target/MavenMCP-1.0-1.8.8.jar` but get "no main manifest attribute"

So I guess I am trying to build/run it incorrectly.

**Comment by AnotherZane** [comment]
Here is a tutorial on how to setup the client: https://youtu.be/5Yrl8TI3uhM

If you need anything else, hit me up on discord (FakeZane#4125)
